### PR TITLE
Access token moved to properties file

### LINKED ISSUE #11: AccessToken shouldn't be managed like this
https://github.com/prithivraj/Surveys/blob/master/app/src/main/java/com/zestworks/surveys/api/SurveyApi.kt

### PR DESCRIPTION
**Pull request by prithivraj**
fixes #11

### CODE REVIEW

**Comment by sleepylee** [comment]
actually, my point was to suggest for a better way of managing the token, as in the real scenario, after receiving AccessToken from a Login/Sign Up activity, accessToken should be stored differently for the purposes like re-using, or pre-login on the next time app launched. So I'd say that this implementation wasn't in the correct idea.

**Comment by sleepylee** [comment]
also for "the place" to add the header, it's not ideal as well with the current implementation as if we need to have more endpoints (in which access token header is mandatory), all of them will be ended up with the same appending piece, dry.

**Comment by prithivraj** [comment]
@sleepylee Yes, I understand now, I will make a change by adding an interceptor to my retrofit so that all requests we make have this property by default. Sounds good?

**Comment by sleepylee** [comment]
yeah that sounds better indeed, @prithivraj

**Comment by prithivraj** [comment]
@sleepylee 
Made the changes here.
https://github.com/prithivraj/Surveys/pull/23

**Pull request merged**
